name: Practise_CI
on:
  push:
    branches:
      - main
  
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install 
      - run: npm test 
      - run: node -c indes.js
      - run: docker build -t babuwa .
      - run:  docker run -p 3000:3000 babuwa